"use client"

import {
  collection,
  getDocs,
  addDoc,
  serverTimestamp,
} from "firebase/firestore"
import { db } from "@/lib/firebase"

const SAMPLE_QUESTS = [
  {
    title: "Event Helper — Orchard Night Market",
    description:
      "We need enthusiastic helpers for a weekend night market at Orchard Road. Tasks include crowd management, guiding visitors, and distributing flyers. Uniform and meals provided. Great energy and punctuality required.",
    category: "events",
    location: "Orchard",
    address: "Orchard Road, Singapore",
    isRemote: false,
    payMin: 14,
    payMax: 18,
    payType: "hourly",
    currency: "SGD",
    duration: "8 hours",
    rankRequired: "F",
    slotsTotal: 15,
    slotsFilled: 6,
    skills: ["communication", "crowd_management"],
    requirements: "Comfortable standing for long hours. Smart casual attire required.",
    source: "direct",
    imageUrls: [],
    status: "active",
    isFeatured: true,
    questGiverId: "system",
    questGiverName: "Muster Guild",
    questGiverAvatar: null,
    questGiverRating: 4.9,
    applicationCount: 8,
  },
  {
    title: "Photography Assistant — Product Shoot",
    description:
      "Assist a professional photographer during a product photography shoot for a local skincare brand. Help set up lighting, manage props, and organise equipment. Portfolio opportunity — work will be credited.",
    category: "photography",
    location: "Marina Bay",
    address: "Marina Bay Sands, Singapore",
    isRemote: false,
    payMin: 22,
    payMax: 28,
    payType: "hourly",
    currency: "SGD",
    duration: "6 hours",
    rankRequired: "E",
    slotsTotal: 2,
    slotsFilled: 0,
    skills: ["photography", "attention_to_detail"],
    requirements: "Basic photography knowledge. Own transport preferred.",
    source: "direct",
    imageUrls: [],
    status: "active",
    isFeatured: false,
    questGiverId: "system",
    questGiverName: "Muster Guild",
    questGiverAvatar: null,
    questGiverRating: 4.9,
    applicationCount: 3,
  },
  {
    title: "Café Barista — Weekend Shifts",
    description:
      "A growing specialty café in Tampines is looking for part-time baristas for weekend morning shifts. Training provided. Good latte art is a bonus but not required.",
    category: "fnb",
    location: "Tampines",
    address: "Tampines Mall, Singapore",
    isRemote: false,
    payMin: 11,
    payMax: 14,
    payType: "hourly",
    currency: "SGD",
    duration: "6 hours",
    rankRequired: "F",
    slotsTotal: 3,
    slotsFilled: 1,
    skills: ["customer_service", "multitasking"],
    requirements: "Customer-facing experience preferred. Able to commit to at least 2 weekends.",
    source: "direct",
    imageUrls: [],
    status: "active",
    isFeatured: false,
    questGiverId: "system",
    questGiverName: "Muster Guild",
    questGiverAvatar: null,
    questGiverRating: 4.9,
    applicationCount: 5,
  },
  {
    title: "Same-Day Parcel Delivery — Island-wide",
    description:
      "Independent parcel delivery for a local boutique. Use your own transport (bicycle, PMD, or car) to deliver 10–15 parcels across Singapore. Flexible hours — complete deliveries anytime 10am–8pm.",
    category: "delivery",
    location: "Island-wide",
    isRemote: false,
    payMin: 60,
    payMax: 100,
    payType: "daily",
    currency: "SGD",
    duration: "1 day",
    rankRequired: "F",
    slotsTotal: 5,
    slotsFilled: 2,
    skills: ["navigation", "time_management"],
    requirements: "Own transport required. Valid driving licence or PMD registration.",
    source: "direct",
    imageUrls: [],
    status: "active",
    isFeatured: false,
    questGiverId: "system",
    questGiverName: "Muster Guild",
    questGiverAvatar: null,
    questGiverRating: 4.9,
    applicationCount: 7,
  },
  {
    title: "IT Setup — Corporate Conference, CBD",
    description:
      "Set up AV equipment, laptops, and networking for a 2-day corporate conference at Suntec City. Must be comfortable troubleshooting on the spot. All equipment provided by client.",
    category: "tech_support",
    location: "CBD / Raffles Place",
    address: "Suntec City, Singapore",
    isRemote: false,
    payMin: 25,
    payMax: 35,
    payType: "hourly",
    currency: "SGD",
    duration: "2 days",
    rankRequired: "D",
    slotsTotal: 4,
    slotsFilled: 1,
    skills: ["networking", "av_setup", "troubleshooting"],
    requirements: "Minimum 1 year IT support experience. Able to work both days.",
    source: "direct",
    imageUrls: [],
    status: "active",
    isFeatured: true,
    questGiverId: "system",
    questGiverName: "Muster Guild",
    questGiverAvatar: null,
    questGiverRating: 4.9,
    applicationCount: 2,
  },
  {
    title: "Admin Assistant — Data Entry & Filing",
    description:
      "Short-term data entry project for a property agency. Digitise physical lease agreements into their CRM system. Work from their Orchard office. Accuracy and speed are key.",
    category: "admin",
    location: "Orchard",
    address: "Orchard Central, Singapore",
    isRemote: false,
    payMin: 12,
    payMax: 15,
    payType: "hourly",
    currency: "SGD",
    duration: "3 days",
    rankRequired: "F",
    slotsTotal: 2,
    slotsFilled: 0,
    skills: ["data_entry", "microsoft_office", "attention_to_detail"],
    requirements: "Proficiency in Excel. Fast typing speed (min 45 WPM).",
    source: "direct",
    imageUrls: [],
    status: "active",
    isFeatured: false,
    questGiverId: "system",
    questGiverName: "Muster Guild",
    questGiverAvatar: null,
    questGiverRating: 4.9,
    applicationCount: 4,
  },
  {
    title: "Brand Activation — Flyer Distribution",
    description:
      "Distribute flyers and samples for a new bubble tea brand launching in Jurong. Friendly, outgoing personalities preferred. You'll be stationed at Jurong Point and JEM on alternating days.",
    category: "marketing",
    location: "Jurong West",
    address: "Jurong Point, Singapore",
    isRemote: false,
    payMin: 10,
    payMax: 13,
    payType: "hourly",
    currency: "SGD",
    duration: "2 days",
    rankRequired: "F",
    slotsTotal: 8,
    slotsFilled: 3,
    skills: ["communication", "sales", "promoter"],
    requirements: "Outgoing personality. No experience needed — training provided.",
    source: "direct",
    imageUrls: [],
    status: "active",
    isFeatured: false,
    questGiverId: "system",
    questGiverName: "Muster Guild",
    questGiverAvatar: null,
    questGiverRating: 4.9,
    applicationCount: 11,
  },
  {
    title: "Primary School Maths Tutor",
    description:
      "A family in Bishan is looking for a reliable tutor for their Primary 4 child (Mathematics). Twice a week, 1.5 hours per session. Experience with MOE syllabus required. Lessons at their home.",
    category: "tutoring",
    location: "Bishan",
    address: "Bishan, Singapore",
    isRemote: false,
    payMin: 30,
    payMax: 45,
    payType: "hourly",
    currency: "SGD",
    duration: "Ongoing",
    rankRequired: "E",
    slotsTotal: 1,
    slotsFilled: 0,
    skills: ["teaching", "mathematics", "patience"],
    requirements: "Minimum A-Level or equivalent. Prior tutoring experience preferred.",
    source: "direct",
    imageUrls: [],
    status: "active",
    isFeatured: false,
    questGiverId: "system",
    questGiverName: "Muster Guild",
    questGiverAvatar: null,
    questGiverRating: 4.9,
    applicationCount: 1,
  },
]

let seeded = false

export async function seedQuestsIfEmpty(): Promise<void> {
  if (seeded) return
  try {
    const questsRef = collection(db, "quests")
    const snap = await getDocs(questsRef)
    if (!snap.empty) {
      seeded = true
      return
    }
    for (const quest of SAMPLE_QUESTS) {
      await addDoc(questsRef, {
        ...quest,
        createdAt: serverTimestamp(),
        updatedAt: serverTimestamp(),
      })
    }
    seeded = true
  } catch (err) {
    console.error("Quest seed failed:", err)
  }
}
